#!/bin/bash


. ./conf_default

# hardware
cluster_name=$CLUSTER-bank

# bank init; creates about 375GB of data
workload="bank"
workload_var=rows
workload_val=13000000
bank_payload_bytes=10240
bank_run_payload_bytes=256
bank_run_max_rate=100


