#!/bin/bash

# 8TB TPCE config

# load default configs and only change non-default settings for this fixture
. ./conf_default

# hardware
crdb_nodes=15
cluster_name=$CLUSTER-8tb
machine_type=m5.4xlarge
vol_size=3000
cloud=aws

# tpce init
workload_val=500000

# tpce run (configure to run  longer as full backup will take a couple # hours)
duration=48h


